name: Build Linux
on:
  workflow_dispatch:
  push:
    tags: ['v*']

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust Nightly
        uses: dtolnay/rust-toolchain@nightly
        with:
          targets: x86_64-unknown-linux-gnu
          components: rust-src

      - name: Install OpenSSL Dependency
        run: |
          sudo apt-get update
          sudo apt-get install -y libssl-dev pkg-config

      - name: Build Tiny Linux Binary
        env:
          RUSTFLAGS: "-Zlocation-detail=none -Zfmt-debug=none -Cpanic=abort"
          CARGO_UNSTABLE_BUILD_STD: "std,panic_abort"
          CARGO_UNSTABLE_BUILD_STD_FEATURES: "optimize_for_size"
        working-directory: "Rust CLI"
        run: |
          cargo build --release --target x86_64-unknown-linux-gnu

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: 007 First Light Save Resigner
          path: "Rust CLI/target/x86_64-unknown-linux-gnu/release/fl007"
